baseurl = "http://www.tpvsports.net"
languagecode = "en-us"
pluralizelisttitles = false
theme = "tpvs16"
title = "The People's Voice Sports Podcast"
[blackfriday]
AngledQuotes = true
Fractions = true
HrefTargetBlank = false
LatexDashes = true
PlainIDAnchors = false
SmartDashes = true
Smartypants = true
SourceRelativeLinksEval = false
[[menu.main]]
identifier = "archive"
name = "archive"
slug = "/archive"
title = "archive"
url = "/podcast"
weight = 2
[[menu.main]]
identifier = "archive"
name = "archive"
slug = "/archive"
title = "archive"
url = "/podcast"
weight = 2
[[menu.main]]
identifier = "home"
name = "home"
title = "home"
url = "/"
weight = 3
[[menu.main]]
identifier = "home"
name = "home"
title = "home"
url = "/"
weight = 3
[params]
PublishDate = "2006-01-02T00:00:00+00:00"
author = "Sir Lawrence Davis"
description = "Welcome to The People's Voice Sports Podcast Website"
episode = "One"
soundcloud = ""
[permalinks]
podcast = "/:year/:month/:day/:slug"
[sitemap]
changefreq = "monthly"
priority = "-1"
